experiment:
  seed: 42
  output_dir: outputs

model:
  name_or_path: "facebook/maskdino-swin-large-ade"  # Replace with desired checkpoint
  models_dir: "./models"
  ignore_mismatched_sizes: false

optimizer:
  lr: 5.0e-05
  betas: [0.9, 0.999]
  weight_decay: 0.01
  eps: 1.0e-08

scheduler:
  warmup_steps: 0
  total_training_steps: null

training:
  batch_size: 2
  gradient_accumulation_steps: 1
  num_epochs: 20
  max_grad_norm: 1.0
  log_every_n_steps: 10
  eval_every_n_epochs: 1
  device: cuda

checkpointing:
  dir: ./checkpoints
  save_every_n_epochs: 1
  monitor: val_loss
  mode: min
  keep_last_n: 3

neptune:
  enabled: false
  project: null
  api_token: null
  run_id: null
  experiment_name: null
  tags: []
  env_path: null
  dependencies_path: null

data:
  dataset_dir: ./data/trees_diseases
  train_split: train
  valid_split: valid
  test_split: test
  num_workers: 4
  image_size: 1024
  remove_empty_annotations: true
